#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [4]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [14]:
arr2=np.array([[1,2,3,4,5]])
print(arr2)
arr2.shape

[[1 2 3 4 5]]


(1, 5)

In [ ]:
## 2d array
arr2=np.array([[1,2,3,4,5],
               [2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [30]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [50]:
## identity matrix
np.eye(5,5,-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [18]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


In [19]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [54]:
## Universal Function
arr=np.array([4,9,16,25,49])
## square root
print(np.sqrt(arr))

## Exponential (np.exp(x)) = e^x  => the exponent of e (2.718...)
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

## Common log (log to the base 10) # log to the base k = np.logk(x) ex np.log2(x)
print(np.log10(arr))



[2. 3. 4. 5. 7.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10
 1.90734657e+21]
[-0.7568025   0.41211849 -0.28790332 -0.13235175 -0.95375265]
[1.38629436 2.19722458 2.77258872 3.21887582 3.8918203 ]
[0.60205999 0.95424251 1.20411998 1.39794001 1.69019608]


In [57]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [32]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [59]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [60]:
## Modify array elements
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [37]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [38]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [39]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [48]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])